name: Check

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Run lint
        run: |
          yarn install --frozen-lockfile
          yarn lint
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Run test
        run: |
          yarn install --frozen-lockfile
          yarn test
        env:
          CI: true
      - name: codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 16
        run: |
          yarn codecov --token="${{ secrets.CODECOV_TOKEN }}"
